CREATE TABLE CLAN (
    id INTEGER PRIMARY KEY,
    name VARCHAR NOT NULL,
    clantag VARCHAR NOT NULL
);


CREATE TABLE MEMBER (
    id INTEGER PRIMARY KEY,
    clanid INTEGER,
    name VARCHAR NOT NULL,
    role VARCHAR NOT NULL,
    wtr INTEGER NOT NULL   
);